/* drop database objects */
DROP VIEW STATEMENTS_N3;
DROP VIEW STATEMENTS;
DROP VIEW STATEMENT_DETAILS;
DROP TABLE TRIPLE;
DROP TABLE BNODE;
DROP TABLE LITERAL;
DROP TABLE RESOURCE;
DROP TABLE CONTEXT;
DROP SEQUENCE SEQ_RESOURCE;
DROP SEQUENCE SEQ_CONTEXT;
DROP SEQUENCE SEQ_LITERAL;
DROP SEQUENCE SEQ_BNODE;
DROP SEQUENCE SEQ_TRIPLE;

COMMIT;
